@Backend_HostAddress = https://localhost:7136

POST {{Backend_HostAddress}}/
Content-Type: application/json
{
  "Url":"https://www.google.com"
}

###

POST {{Backend_HostAddress}}/
Content-Type: application/json
{
  "Url":"https://www.youtube.com"
}

###

GET {{Backend_HostAddress}}/google.com

###

GET {{Backend_HostAddress}}/youtube.com
