@Backend_HostAddress = https://localhost:7136

POST {{Backend_HostAddress}}/todoitems
Content-Type: application/json

{
  "name":"clean room",
  "isComplete":false
}

###

GET {{Backend_HostAddress}}/todoitems

###

GET {{Backend_HostAddress}}/todoitems/2

###

PUT {{Backend_HostAddress}}/todoitems/{{id}}
Content-Type: application/json

{
  "id": 1,
  "name": "cut hair",
  "isComplete": false
}

###

@id=1
DELETE {{Backend_HostAddress}}/todoitems/{{id}}

###
